### PR TITLE
fix those lspoutofbounds

### LINKED ISSUE #198: LSPPOS outofbounds
I see a ton of these warnings often -

```
WARN - p4intellij.utils.DocumentUtils - LSPPOS outofbounds : Position [
  line = 24
  character = 9
] line : foo = 2.5 column : 9 offset : 702 
```

I'm not entirely sure what's causing this, just want to document it here for now.

### PR DESCRIPTION
**Pull request by swissiety**
- [x] fix outofbounds for linecount -> off by one
- [x] add min bound check
- [x] fix offsettolsp()
- [x] log.info to debug 

closes #198

### CODE REVIEW

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java [hunk 1]
```diff
@@ -99,6 +97,9 @@ public static Position offsetToLSPPos(LogicalPosition position, Editor editor) {
      */
     public static Position offsetToLSPPos(Editor editor, int offset) {
         return computableReadAction(() -> {
+            if (editor.isDisposed()) {
+                return null;
```
Comment (nixel2007) [inline src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:101]: please add @Nullable annotation

**Comment by swissiety** [comment]
why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?

"Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java [hunk 2]
```diff
@@ -109,55 +128,51 @@ public static Position offsetToLSPPos(Editor editor, int offset) {
...
+            if (pos.getCharacter() >= lineText.length()) {
+                LOG.debug(String.format("LSPPOS outofbounds: %s, line : %s, column : %d, offset : %d", pos,
+                        lineText, column, offset));
+            }
+            int docLength = doc.getTextLength();
+            if (offset > docLength) {
+                LOG.debug(String.format("Offset greater than text length : %d > %d", offset, docLength));
+            }
+            return Math.min(max(offset, 0), docLength);
+
```
Comment (NipunaRanasinghe) [inline src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:157]: @swissiety Sorry If I'm missing your point, but may I know the reason for removing the exception handling in here?

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java [hunk 3]
```diff
@@ -109,55 +128,51 @@ public static Position offsetToLSPPos(Editor editor, int offset) {
...
             }
+            Document doc = editor.getDocument();
+            int line = max(0, Math.min(pos.getLine(), doc.getLineCount()-1));
+            String lineText = doc.getText(DocumentUtil.getLineTextRange(doc, line));
+            final int endCharInLine = max(0, min(lineText.length(), pos.getCharacter()));
+            String lineTextForPosition = endCharInLine > 0 ? lineText.substring(0, endCharInLine) : "";
+            int tabs = StringUtil.countChars(lineTextForPosition, '\t');
+            int tabSize = getTabSize(editor);
+            int column = tabs * tabSize + lineTextForPosition.length() - tabs;
+            return new LogicalPosition(line, column);
```
Comment (NipunaRanasinghe) [inline src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:175]: @swissiety Sorry If I'm missing your point, but may I know the reason for removing the exception handling in here?

Comment (swissiety) [reply src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:175]: `IndexOutOfBoundsException` was thrown because of using `doc.getLineCount()` as the last possible line - but the last line is doc.getLineCount()-1. Additionally negative values for the "char in line" have been possible wich made it possible for `substring(..)` to throw this exception. Now there shouldnt be a possibility to throw this exception.

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java (hunk 2 above)
Comment (swissiety) [reply src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:157]: see below ;)

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java [hunk 4]
```diff
@@ -38,6 +39,10 @@
     public static final String WIN_SEPARATOR = "\r\n";
     public static final String LINUX_SEPARATOR = "\n";
 
+    public static int getTabSize(Editor editor) {
```
Comment (NipunaRanasinghe) [inline src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:42]:
```suggestion
    private static int getTabSize(Editor editor) {
```

Comment (NipunaRanasinghe) [inline src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:42]: Lets move down this new util method, as its used only within the class (hence should be private).

**Comment by NipunaRanasinghe** [comment]
> why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?
> 
> "Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"

Hmm that's strange.. I tried locally after applying your changes and couldn't reproduce this error.

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java (hunk 4 above)
Comment (swissiety) [reply src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:42]: it could be used in EditorEventManager for `FormattingOptions( .. )`, too

**Comment by swissiety** [comment]
> > why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?
> > "Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"
> 
> Hmm that's strange.. I tried to build locally after applying your changes and couldn't reproduce this error.

btw. is there a way to make `gitVersionCalculator.calculateVersion("v")` from `build.gradle` work locally? Currently i replaced it to be able compile - and i dont think thats the way to do

File: src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java (hunk 3 above)
Comment (NipunaRanasinghe) [reply src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java]: @swissiety got it.. Thanks!

**Comment by NipunaRanasinghe** [comment]
> > > why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?
> > > "Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"
> > 
> > 
> > Hmm that's strange.. I tried to build locally after applying your changes and couldn't reproduce this error.
> 
> btw. is there a way to make `gitVersionCalculator.calculateVersion("v")` from `build.gradle` work locally? Currently im replacing it to be able to compile - and i dont think thats the way to do.

@swissiety I can locally run the `build.gradle` without any issues. Whats the exact error message you are having?

**Comment by swissiety** [comment]
> > > > why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?
> > > > "Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"
> > > 
> > > 
> > > Hmm that's strange.. I tried to build locally after applying your changes and couldn't reproduce this error.
> > 
> > 
> > btw. is there a way to make `gitVersionCalculator.calculateVersion("v")` from `build.gradle` work locally? Currently im replacing it to be able to compile - and i dont think thats the way to do.
> 
> @swissiety I can locally run the `build.gradle` without any issues. Whats the exact error message you are having?

maybe there is some naming convention for branches? The error message is the following:

Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'lsp4intellij'.
Caused by: com.github.gradle_git_version_calculator.Exceptions.GitCommandError: Status code: 128
Stderr:
fatal: No names found, cannot describe anything.

	at com.github.gradle_git_version_calculator.git_commands.AbstractGitCommand.validateResult(AbstractGitCommand.java:77)
	at com.github.gradle_git_version_calculator.git_commands.AbstractGitCommand.call(AbstractGitCommand.java:38)
	at com.github.gradle_git_version_calculator.GitRepository.getLatestTag(GitRepository.java:27)
	at com.github.gradle_git_version_calculator.GitVersionCalculator.calculateSemVer(GitVersionCalculator.java:29)
	at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension.calculateVersion(GitVersionCalculatorExtension.java:39)
	at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension.calculateVersion(GitVersionCalculatorExtension.java:47)
	at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension$calculateVersion.call(Unknown Source)
	at build_cnbuel1bd58ohez3r4api4pk2.run(~/workspace/lsp4intellij/build.gradle:18)

**Review by NipunaRanasinghe — APPROVED** [review]

**Comment by NipunaRanasinghe** [comment]
> > > > > why does :compileJava from the pipeline find another `getTabSize()` in a file where there is only a single definition given?
> > > > > "Users/runner/work/lsp4intellij/lsp4intellij/src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java:179: error: method getTabSize(Editor) is already defined in class DocumentUtils"
> > > > 
> > > > 
> > > > Hmm that's strange.. I tried to build locally after applying your changes and couldn't reproduce this error.
> > > 
> > > 
> > > btw. is there a way to make `gitVersionCalculator.calculateVersion("v")` from `build.gradle` work locally? Currently im replacing it to be able to compile - and i dont think thats the way to do.
> > 
> > 
> > @swissiety I can locally run the `build.gradle` without any issues. Whats the exact error message you are having?
> 
> maybe there is some naming convention for branches? The error message is the following:
> 
> Exception is:
> org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'lsp4intellij'.
> Caused by: com.github.gradle_git_version_calculator.Exceptions.GitCommandError: Status code: 128
> Stderr:
> fatal: No names found, cannot describe anything.
> 
> ```
> at com.github.gradle_git_version_calculator.git_commands.AbstractGitCommand.validateResult(AbstractGitCommand.java:77)
> at com.github.gradle_git_version_calculator.git_commands.AbstractGitCommand.call(AbstractGitCommand.java:38)
> at com.github.gradle_git_version_calculator.GitRepository.getLatestTag(GitRepository.java:27)
> at com.github.gradle_git_version_calculator.GitVersionCalculator.calculateSemVer(GitVersionCalculator.java:29)
> at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension.calculateVersion(GitVersionCalculatorExtension.java:39)
> at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension.calculateVersion(GitVersionCalculatorExtension.java:47)
> at com.github.gradle_git_version_calculator.gradle.GitVersionCalculatorExtension$calculateVersion.call(Unknown Source)
> at build_cnbuel1bd58ohez3r4api4pk2.run(~/workspace/lsp4intellij/build.gradle:18)
> ```

@swissiety Unfortunately I cannot reproduce this locally couldnt find any similar issue reported at https://github.com/PawelJ-PL/gradle-git-version-calculator :neutral_face:
